# Generated by Django 2.0 on 2019-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_auto_20191118_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='picture_title',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
