# Generated by Django 2.0 on 2019-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_meme_picture_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.TextField(max_length=1000000)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('picture_title', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='meme',
            name='picture_title',
        ),
        migrations.AddField(
            model_name='meme',
            name='extension',
            field=models.CharField(default='.jpg', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meme',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
