# Generated by Django 2.0 on 2019-12-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_auto_20191127_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
