# Generated by Django 2.0 on 2019-12-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0007_auto_20191206_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='extension',
            field=models.CharField(choices=[('jpg', 'jpg'), ('png', 'png'), ('gif', 'gif'), ('jpeg', 'jpeg')], max_length=16),
        ),
    ]
