# Generated by Django 2.0 on 2019-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0008_auto_20191206_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='bought',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
