# Generated by Django 2.0 on 2019-12-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_meme_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='bought',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
